#!/usr/bin/env bash
#
# Configures the extensions and settings typically I use with VS Code.
#
# Usage: ./setup

# Install extensions
code \
    --install-extension adpyke.vscode-sql-formatter \
    --install-extension brittanychiang.halcyon-vscode \
    --install-extension christian-kohler.path-intellisense \
    --install-extension dotjoshjohnson.xml
    --install-extension editorconfig.editorconfig \
    --install-extension esbenp.prettier-vscode \
    --install-extension foxundermoon.shell-format \
    --install-extension github.github-vscode-theme \
    --install-extension hashicorp.terraform \
    --install-extension mechatroner.rainbow-csv \
    --install-extension mermade.openapi-lint \
    --install-extension michelemelluso.code-beautifier \
    --install-extension mikestead.dotenv \
    --install-extension ms-azuretools.vscode-docker \
    --install-extension ms-dotnettools.csharp \
    --install-extension ms-python.python \
    --install-extension ms-toolsai.jupyter \
    --install-extension ms-vscode-remote.vscode-remote-extensionpack \
    --install-extension ms-vscode.cmake-tools \
    --install-extension ms-vscode.cpptools \
    --install-extension ms-vscode.powershell \
    --install-extension naumovs.color-highlight \
    --install-extension rust-lang.rust \
    --install-extension ryu1kn.partial-diff \
    --install-extension sdras.night-owl \
    --install-extension simonsiefke.svg-preview \
    --install-extension tamasfe.even-better-toml \
    --install-extension tyriar.sort-lines \
    --install-extension waderyan.gitblame \
    --install-extension yummygum.city-lights-icon-vsc \
    --install-extension yummygum.city-lights-theme \
    --install-extension zxh404.vscode-proto3

# Copy settings over
mkdir -p "$HOME/Library/Application Support/Code/User"

[ ! -f "$HOME/Library/Application Support/Code/User/settings.json" ] \
    || mv "$HOME/Library/Application Support/Code/User/settings.json" \
        "$HOME/Library/Application Support/Code/User/settings.json.bak" \
    && cp "$HOME/github/utilities/VS Code/settings.json" \
        "$HOME/Library/Application Support/Code/User/settings.json"

[ ! -f "$HOME/Library/Application Support/Code/User/keybindings.json" ] \
    || mv "$HOME/Library/Application Support/Code/User/keybindings.json" \
        "$HOME/Library/Application Support/Code/User/keybindings.json.bak" \
    && cp "$HOME/github/utilities/VS Code/keybindings.json" \
        "$HOME/Library/Application Support/Code/User/keybindings.json"
