#!/usr/bin/env bash
#
# Installs the PIP packages I typically use outside of envs.

set -e

pip3 install \
    virtualenv \
    'python-language-server[all]' flake8 pep8 pytest \
    numpy scipy pandas jupyterlab tqdm \
    kaggle
