#!/usr/bin/env bash
#
# Installs the PIP packages I typically use globally.

set -e

pip3 install \
    'python-language-server[all]' \
    flake8 \
    ipython \
    jupyterlab \
    kaggle \
    mypy \
    numpy \
    pandas \
    pyls-isort \
    pytest \
    scipy \
    tqdm

mkdir -p ~/.config/mypy
cp ~/github/utilities/Python/config ~/.config/mypy
