#!/usr/bin/env bash
#
# Configures my system Python installation.
#
# Usage: ./setup

pip3 install --upgrade \
    black \
    ipython \
    kaggle \
    mypy \
    numpy \
    pandas \
    proselint \
    pylint \
    python-language-server[all] \
    tqdm

# Configuration for pip
mkdir -p "$HOME/.pip/pip.conf" \
    && cp "$HOME/github/utilities/Python/pip.conf" "$HOME/.pip/pip.conf"

# Configuration for MyPy
mkdir -p "$HOME/.config/mypy" \
    && cp "$HOME/github/utilities/Python/config" "$HOME/.config/mypy/config"
