#!/usr/bin/env bash
#
# Configures the packages and settings typically I use with Atom.

# Install plugin dependencies
pip3 install \
    'python-language-server[all]' \
    IPython

# Install plugins
apm install \
  atom-ide-debugger-python \
  atom-ide-ui \
  atom-language-r \
  file-icons \
  git-history \
  git-time-machine \
  ide-python \
  language-docker \
  language-jenkinsfile \
  language-julia \
  language-latex \
  language-markdown \
  language-scala \
  minimap \
  minimap-cursorline \
  pigments \
  python-indent \
  sort-lines \
  split-diff

# Import settings
mkdir -p ~/.atom
ln -s ~/github/utilities/Atom/config.cson ~/.atom/config.cson
